// src/utils/constants.js
export const INITIAL_STATE = {
  penyusun: "",
  sekolah: "",
  mapel: "",
  fase: "Fase D",
  kelas: "",
  semester: "Ganjil",
  alokasiWaktu: "",
  tahunPenyusunan: "2024/2025",
  elemen: "",
  materi: "",
  jenjang: "",
  profilPancasila: [],
  kompetensiAwal: "",
  sarpras: "",
  modelPembelajaran: "Problem Based Learning (PBL)",
  metodePembelajaran: "",
  pendekatanPembelajaran: "Saintifik",
  cp: "",
  tp: "",
  pemahamanBermakna: "",
  pertanyaanPemantik: "",
  pendahuluan: "",
  kegiatanInti: "",
  penutup: "",
  asesmen: "",
  rubrikPenilaian: "",
  refleksi: "",
  pengayaanRemedial: "",
  glosarium: "",
  daftarPustaka: "",
};
